"""Auto migration

Revision ID: 15a5fe72df0e
Revises: 58f1f1459724
Create Date: 2025-06-24 17:43:50.486080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15a5fe72df0e'
down_revision = '58f1f1459724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
