"""Auto migration

Revision ID: 2bd3a260845e
Revises: a4b93442d7da
Create Date: 2025-06-23 10:24:26.537594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd3a260845e'
down_revision = 'a4b93442d7da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
