"""Add likes column to Comment

Revision ID: 363f31a5b2f8
Revises: 
Create Date: 2025-06-21 19:02:07.725554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363f31a5b2f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('likes')

    # ### end Alembic commands ###
