"""fresh migration

Revision ID: 3e89d3e52c20
Revises: 62fb175cc855
Create Date: 2025-06-24 17:58:50.173839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e89d3e52c20'
down_revision = '62fb175cc855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
