"""Add new column X

Revision ID: 4c75966c5f23
Revises: 3e89d3e52c20
Create Date: 2025-06-24 18:09:50.555854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c75966c5f23'
down_revision = '3e89d3e52c20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
