"""Auto migration

Revision ID: 58f1f1459724
Revises: 2bd3a260845e
Create Date: 2025-06-24 17:32:38.699399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f1f1459724'
down_revision = '2bd3a260845e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
