"""describe your change

Revision ID: 62fb175cc855
Revises: 15a5fe72df0e
Create Date: 2025-06-24 17:43:50.590025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62fb175cc855'
down_revision = '15a5fe72df0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
