"""Auto migration

Revision ID: a4b93442d7da
Revises: 6f82e37b364b
Create Date: 2025-06-23 10:16:24.467052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4b93442d7da'
down_revision = '6f82e37b364b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.drop_column('wew')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wew', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
